version: "3.8"
services:
    nodeserver:
        restart: always
        build:
            context: .
        ports:
            - "5999:5999"
    nginx:
        restart: always
        build:
            context: ./nginx.conf
        ports:
            - "80:80"